print("Welcome to the Band Name Generator.")
street = input("What's the name of the city you grew up in?\n")
pet = input("What's your pet's name?\n")
nick = input("What's your nick name?\n")
adr = input("What's your address?\n")
print("Your band name could be " + street + " " + pet + " " + nick+ " " + adr)